#!/bin/sh
# Author: Scott Chen 

usage()
{
    echo "Kermit Easy Command (Scott Chen)"
    echo ""
    echo "Usage:"
    echo "  `basename $0` <tty-device> <speed>"
    echo "  `basename $0` ls|list"
    echo "  `basename $0` -d <tty-device>"
    echo "  `basename $0` -s <tty-device>"
    echo "  `basename $0` tell <user> <messages...>"
    echo ""
    echo "Example:"
    echo "  `basename $0` ttyS0 115200  --> connect to /dev/ttyS0, speed=115200"
    echo "  `basename $0` ttyS0         --> connect to /dev/ttyS0, speed=115200"
    echo "  `basename $0` ttyUSB1 9600  --> connect to /dev/ttyUSB1, speed=9600"
    echo "  `basename $0` 2 9600        --> connect to /dev/ttyUSB2, speed=9600"
    echo "  `basename $0` 2             --> connect to /dev/ttyUSB2, speed=115200"
    echo "  `basename $0` ls            --> show kermit connections and lock files"
    echo "  `basename $0` -d ttyUSB0    --> terminate connection to /dev/ttyUSB0"
    echo "  `basename $0` -d 1          --> terminate connection to /dev/ttyUSB1"
    echo "  `basename $0` tell scott hi --> send a message "hi" to scott in all tty"
    echo ""
    exit 
}

get_platform_name() {
    output=result.txt
    tty=/dev/$1
    cmd1="cat $tty"
    #cmd2="cat /flash/data0/platform_name"

    if [ -f "/var/lock/LCK..$1" ]; then
        return 
    fi
    
    $cmd1 > $output 2> /dev/null &
    #echo "$cmd2" > $tty
    sleep 1
    result=`cat $output | grep -v cat | grep -v ']'`
    result=`echo $result`
    kill -9 $! 2>&1 > /dev/null
    echo "$result"
    rm -f $output
}

gen_kermitrc()
{
    local tty=$1
    local speed=$2
    local result=`get_platform_name $tty`

    echo "  # $result "
    echo "  set line /dev/$1"
    echo "  set speed $speed"
    echo "  set carrier-watch off"
    echo "  set flow-control none"
    echo "  log session ~/km.log"
    echo "  connect"
}

run_km()
{
    rcfile=/tmp/$USER-$1-$2
    gen_kermitrc $1 $2 > $rcfile
    echo "kermit -y $rcfile"
    cat $rcfile
    kermit -y $rcfile && rm -f $rcfile
}

kermit_mode()
{
    local tty=$1
    local speed=$2
    if [ $# -lt 1 ]; then
        list_mode
        exit
    fi
    
    if [ "$1" -eq $1 2>/dev/null ]; then
        tty=ttyUSB$1
    else
        tty=$1
    fi
    
    if [ -z "$2" ]; then
        speed=115200
    fi
    if [ -n "`ps aux | grep kermit | grep $tty-`" ]; then
        printf "Device /dev/$tty is locked.\n"
        exit
    fi
    run_km $tty $speed
}

list_km_info2()
{
    ps aux | grep kermit | grep -v grep | grep -v defunc | \
        sed -e 's/\/tmp\/[a-zA-Z0-9]\+-\([a-zA-Z0-9]\+\)-[0-9]\+/\1/g' | \
        awk '{ printf "%-10s | %-10s | %-10s | km -d %-15s\n\r", $(NF), $1, $2, $(NF)}'
}

list_km_info()
{
    local tmpfile=info.txt
    ps aux | grep kermit | grep -v grep | grep -v defunc | \
        awk '{ printf "%-10s %-10s %-10s\n", $1, $2, $(NF)}' > $tmpfile
    while read name pid tty; do
        local ttyname=`echo $tty | sed -e 's/\/tmp\/[a-zA-Z0-9]\+-\([a-zA-Z0-9]\+\)-[0-9]\+/\1/g'`
        local platform=`cat $tty | head -n 1  | awk '{ print $2}' | sed -e 's/\r//g'`
        if [[ $platform = line || $platform = "" ]]; then
           platform='N/A'
        fi
	    if [[ $platform != 'StarScreamB_SideA' && $platform != 'StarScreamB_SideB' && \
	          $platform != 'Jetfire_SideA' && $platform != 'Jetfire_SideB' && \
	          $platform != 'Beachcomber_SideA' && $platform != 'Beachcomber_SideB' && \
	          $platform != 'Devastator_SideA' && $platform != 'Devastator_SideB' && \
	          $platform != 'Megatron_SideA' && $platform != 'Megatron_SideB' ]] ; then
	       platform='N/A'
	    fi
         printf "%-10s | %-10s | %-10s | km -d %-10s | %-10s \n\r" $ttyname $name $pid $ttyname $platform
    done < $tmpfile
    rm -f $tmpfile 
}

list_mode()
{
    echo `ls /dev/ttyUSB*`
    echo -ne "-----------+------------+------------+------------------+-------------------\n\r" 
    echo -ne " TTY       | User       | Pid        | Release command  | Platform name     \n\r" 
    echo -ne "-----------+------------+------------+------------------+-------------------\n\r" 
    list_km_info
    echo -ne "-----------+------------+------------+------------------+-------------------\n\r" 
}

delete_mode()
{
    local key=$2
    if [ "$key" -eq $key 2> /dev/null ]; then
        key=ttyUSB$2
    fi
    local lockfile="/var/lock/LCK..$key"
    if [ -f $lockfile ]; then
        pid=`list_km_info | grep $key | awk -F "|" '{print $3}'`
        victim=`list_km_info | grep $key | awk -F "|" '{print $2}'`
        send_messages tell $victim "Your ($key) was stolen"
        echo -ne "Terminating $key (PID=`echo $pid`)\n\r"
        sudo kill -9 $pid 2> /dev/null
        sudo rm -f $lockfile 2> /dev/null
    fi
}

get_available_users()
{
    who | grep -v USER | awk '{ print $1}' | sort | uniq | awk '{ printf "%s ", $1}'
}

check_user()
{
    local user=$1
    export valid=n
    if [ -n $user ]; then
        for guy in `get_available_users`; do
            if [ "$guy" = "$user" ]; then
                valid=y
            fi
        done
    fi
    if [ $valid = n ]; then
        echo "User '$user' is not available, send to one of below instead: "
        echo "  `get_available_users`"
        echo ""
        exit
    fi
}

send_messages()
{
    export from=`whoami`
    shift
    export user=$1
    shift
    export msg=$@
    check_user $user
    w | grep "$user" | awk '{ printf "echo \$from said: \$msg | write \$user %s\n", $2}' 2>/dev/null | sh 
    echo "To:       $user"
    echo "Messages: $msg"
    echo "Status:   Sent!"
    unset msg
    unset from
    unset user
}

tell_mode()
{
    if [ $# -lt 1 ]; then
        echo ""
        echo "Usage: `basename $0` tell <user> <messages...>"
        echo ""
        echo "user:"
        echo "  `get_available_users`"
        return
    fi
    send_messages $@
}

steal_mode()
{
    delete_mode $@
    echo -e "Don't be evil!\n\r"
    sleep 1
    echo -e "Stealing tty... haha...\n\r"
    sleep 2
    shift
    kermit_mode $@
}

case $1 in
    help|-h)
        usage
    ;;
    list|ls)
        list_mode $@
    ;;
    delete|release|-d)
        delete_mode $@
        list_mode $@
    ;;
    steal|-s)
        steal_mode $@
    ;;
    tell)
        tell_mode $@
    ;;
    test)
        list_km_info2
    ;;
    *)
        kermit_mode $@
    ;;
esac

